### PR TITLE
Examples rework

### PR DESCRIPTION
**Pull request by joshmgrant**
Time to make the doughnuts...

This PR is to move this project to be the single source of truth for public-facing Python with Sauce Labs examples. The plan is to add examples using

- pytest
- robotframework

that show how to test web and native mobile apps against

- desktop web (VDC)
- mobile Web (emu/sim), and
- native applications (RDC).

### CODE REVIEW

**Comment by joshmgrant** [comment]
This is ready for review @spider-sauce. CI is failing but we might want to review that setup in light of these changes.

**Comment by titusfortner** [comment]
@joshmgrant would you like to maintain git history for these repos before merging? I can walk you through what I did for Ruby ones.

**Comment by joshmgrant** [comment]
@titusfortner I don't need to preserve the history in this PR. Squash and commit works in that case.

**Comment by spider-sauce** [comment]
@joshgrantsauce I updated the config.yml so all tests passed. Can we change the build name to something like this whenever it applies: `Python-<Framework>-Selenium-<Build_Tag>`?

**Pull request merged**
